from datetime import datetime

from aiogram.filters.callback_data import CallbackData
from aiogram.types import User, Chat, Message, Update, CallbackQuery, InlineKeyboardButton, InlineKeyboardMarkup
from aiogram3_calendar.calendar_types import DialogCalendarAction, DialogCalendarCallback

TEST_USER = User(id=1234, is_bot=False, first_name='Test', last_name='Bot', username='testbot',
                 language_code='ru', is_premium=None, added_to_attachment_menu=None, can_join_groups=None,
                 can_read_all_group_messages=None, supports_inline_queries=None)

TEST_USER_CHAT = Chat(id=1234, type='private', title=None, username=TEST_USER.username, first_name=TEST_USER.first_name,
            last_name=TEST_USER.last_name, is_forum=None, photo=None, active_usernames=None, available_reactions=None,
            accent_color_id=None, background_custom_emoji_id=None, profile_accent_color_id=None,
            profile_background_custom_emoji_id=None, emoji_status_custom_emoji_id=None,
            emoji_status_expiration_date=None, bio=None, has_private_forwards=None,
            has_restricted_voice_and_video_messages=None, join_to_send_messages=None, join_by_request=None,
            description=None, invite_link=None, pinned_message=None, permissions=None, slow_mode_delay=None,
            message_auto_delete_time=None, has_aggressive_anti_spam_enabled=None, has_hidden_members=None,
            has_protected_content=None, has_visible_history=None, sticker_set_name=None, can_set_sticker_set=None,
            linked_chat_id=None, location=None)


def get_message(text: str):
    return Message(message_id=123, date=datetime.now(), chat=TEST_USER_CHAT, message_thread_id=None, from_user=TEST_USER,
                   sender_chat=TEST_USER_CHAT, sender_boost_count=None, forward_origin=None, is_topic_message=None,
                   is_automatic_forward=None, reply_to_message=None, external_reply=None, quote=None,
                   reply_to_story=None, via_bot=None, edit_date=None, has_protected_content=None, media_group_id=None,
                   author_signature=None,
                   text=text,
                   entities=None, link_preview_options=None, animation=None, audio=None, document=None, photo=None, sticker=None,
                   story=None, video=None, video_note=None, voice=None, caption=None, caption_entities=None, has_media_spoiler=None,
                   contact=None, dice=None, game=None, poll=None, venue=None, location=None, new_chat_members=None,
                   left_chat_member=None, new_chat_title=None, new_chat_photo=None, delete_chat_photo=None, group_chat_created=None,
                   supergroup_chat_created=None, channel_chat_created=None, message_auto_delete_timer_changed=None, migrate_to_chat_id=None,
                   migrate_from_chat_id=None, pinned_message=None, invoice=None, successful_payment=None, users_shared=None, chat_shared=None,
                   connected_website=None, write_access_allowed=None, passport_data=None, proximity_alert_triggered=None, boost_added=None,
                   forum_topic_created=None, forum_topic_edited=None, forum_topic_closed=None, forum_topic_reopened=None, general_forum_topic_hidden=None,
                   general_forum_topic_unhidden=None, giveaway_created=None, giveaway=None, giveaway_winners=None, giveaway_completed=None,
                   video_chat_scheduled=None, video_chat_started=None, video_chat_ended=None, video_chat_participants_invited=None,
                   web_app_data=None, reply_markup=None, forward_date=None, forward_from=None, forward_from_chat=None,
                   forward_from_message_id=None, forward_sender_name=None, forward_signature=None, user_shared=None)


def get_update(message: Message = None, call: CallbackQuery = None):
    return Update(
        update_id=187,
        message=message if message else None,
        edited_message=None,
        channel_post=None,
        edited_channel_post=None,
        inline_query=None,
        chosen_inline_result=None,
        callback_query=call if call else None,
        shipping_query=None,
        pre_checkout_query=None,
        poll=None,
        poll_answer=None,
        my_chat_member=None,
        chat_member=None,
        chat_join_request=None
    )


call = CallbackQuery(
    id='5452542561866118482',
    from_user=TEST_USER,
    chat_instance='3245609804673994185',
    message=Message(message_id=807, date=datetime.now(),
                      chat=TEST_USER_CHAT, message_thread_id=None,
                      from_user=User(id=6712088492, is_bot=True, first_name='salary_agregator_bot', last_name=None,
                                     username='salary_agregator_bot', language_code=None, is_premium=None,
                                     added_to_attachment_menu=None, can_join_groups=None, can_read_all_group_messages=None,
                                     supports_inline_queries=None), sender_chat=None, sender_boost_count=None,
                      forward_origin=None, is_topic_message=None, is_automatic_forward=None, reply_to_message=None,
                      external_reply=None, quote=None, reply_to_story=None, via_bot=None, edit_date=1709202719,
                      has_protected_content=None, media_group_id=None, author_signature=None,
                      text='Выберите дату начала периода:', entities=None, link_preview_options=None, animation=None,
                      audio=None, document=None, photo=None, sticker=None, story=None, video=None, video_note=None,
                      voice=None, caption=None, caption_entities=None, has_media_spoiler=None, contact=None, dice=None,
                      game=None, poll=None, venue=None, location=None, new_chat_members=None, left_chat_member=None,
                      new_chat_title=None, new_chat_photo=None, delete_chat_photo=None, group_chat_created=None,
                      supergroup_chat_created=None, channel_chat_created=None, message_auto_delete_timer_changed=None,
                      migrate_to_chat_id=None, migrate_from_chat_id=None, pinned_message=None, invoice=None,
                      successful_payment=None, users_shared=None, chat_shared=None, connected_website=None,
                      write_access_allowed=None, passport_data=None, proximity_alert_triggered=None, boost_added=None,
                      forum_topic_created=None, forum_topic_edited=None, forum_topic_closed=None, forum_topic_reopened=None,
                      general_forum_topic_hidden=None, general_forum_topic_unhidden=None, giveaway_created=None,
                      giveaway=None, giveaway_winners=None, giveaway_completed=None, video_chat_scheduled=None,
                      video_chat_started=None, video_chat_ended=None, video_chat_participants_invited=None,
                      web_app_data=None, reply_markup=InlineKeyboardMarkup(inline_keyboard=[[InlineKeyboardButton(
            text='2023', url=None, callback_data='dialog_calendar:4:2023:-1:-1', web_app=None, login_url=None,
            switch_inline_query=None, switch_inline_query_current_chat=None, switch_inline_query_chosen_chat=None,
            callback_game=None, pay=None), InlineKeyboardButton(text='Feb', url=None,
                                                                callback_data='dialog_calendar:1:2023:-1:-1', web_app=None,
                                                                login_url=None, switch_inline_query=None,
                                                                switch_inline_query_current_chat=None,
                                                                switch_inline_query_chosen_chat=None, callback_game=None,
                                                                pay=None)], [InlineKeyboardButton(text='Mo', url=None,
                                                                                                  callback_data='dialog_calendar:0:-1:-1:-1',
                                                                                                  web_app=None,
                                                                                                  login_url=None,
                                                                                                  switch_inline_query=None,
                                                                                                  switch_inline_query_current_chat=None,
                                                                                                  switch_inline_query_chosen_chat=None,
                                                                                                  callback_game=None,
                                                                                                  pay=None),
                                                                             InlineKeyboardButton(text='Tu', url=None,
                                                                                                  callback_data='dialog_calendar:0:-1:-1:-1',
                                                                                                  web_app=None,
                                                                                                  login_url=None,
                                                                                                  switch_inline_query=None,
                                                                                                  switch_inline_query_current_chat=None,
                                                                                                  switch_inline_query_chosen_chat=None,
                                                                                                  callback_game=None,
                                                                                                  pay=None),
                                                                             InlineKeyboardButton(text='We', url=None,
                                                                                                  callback_data='dialog_calendar:0:-1:-1:-1',
                                                                                                  web_app=None,
                                                                                                  login_url=None,
                                                                                                  switch_inline_query=None,
                                                                                                  switch_inline_query_current_chat=None,
                                                                                                  switch_inline_query_chosen_chat=None,
                                                                                                  callback_game=None,
                                                                                                  pay=None),
                                                                             InlineKeyboardButton(text='Th', url=None,
                                                                                                  callback_data='dialog_calendar:0:-1:-1:-1',
                                                                                                  web_app=None,
                                                                                                  login_url=None,
                                                                                                  switch_inline_query=None,
                                                                                                  switch_inline_query_current_chat=None,
                                                                                                  switch_inline_query_chosen_chat=None,
                                                                                                  callback_game=None,
                                                                                                  pay=None),
                                                                             InlineKeyboardButton(text='Fr', url=None,
                                                                                                  callback_data='dialog_calendar:0:-1:-1:-1',
                                                                                                  web_app=None,
                                                                                                  login_url=None,
                                                                                                  switch_inline_query=None,
                                                                                                  switch_inline_query_current_chat=None,
                                                                                                  switch_inline_query_chosen_chat=None,
                                                                                                  callback_game=None,
                                                                                                  pay=None),
                                                                             InlineKeyboardButton(text='Sa', url=None,
                                                                                                  callback_data='dialog_calendar:0:-1:-1:-1',
                                                                                                  web_app=None,
                                                                                                  login_url=None,
                                                                                                  switch_inline_query=None,
                                                                                                  switch_inline_query_current_chat=None,
                                                                                                  switch_inline_query_chosen_chat=None,
                                                                                                  callback_game=None,
                                                                                                  pay=None),
                                                                             InlineKeyboardButton(text='Su', url=None,
                                                                                                  callback_data='dialog_calendar:0:-1:-1:-1',
                                                                                                  web_app=None,
                                                                                                  login_url=None,
                                                                                                  switch_inline_query=None,
                                                                                                  switch_inline_query_current_chat=None,
                                                                                                  switch_inline_query_chosen_chat=None,
                                                                                                  callback_game=None,
                                                                                                  pay=None)], [
                                                                                                InlineKeyboardButton(
                                                                                                    text=' ', url=None,
                                                                                                    callback_data='dialog_calendar:0:-1:-1:-1',
                                                                                                    web_app=None,
                                                                                                    login_url=None,
                                                                                                    switch_inline_query=None,
                                                                                                    switch_inline_query_current_chat=None,
                                                                                                    switch_inline_query_chosen_chat=None,
                                                                                                    callback_game=None,
                                                                                                    pay=None),
                                                                                                InlineKeyboardButton(
                                                                                                    text=' ', url=None,
                                                                                                    callback_data='dialog_calendar:0:-1:-1:-1',
                                                                                                    web_app=None,
                                                                                                    login_url=None,
                                                                                                    switch_inline_query=None,
                                                                                                    switch_inline_query_current_chat=None,
                                                                                                    switch_inline_query_chosen_chat=None,
                                                                                                    callback_game=None,
                                                                                                    pay=None),
                                                                                                InlineKeyboardButton(
                                                                                                    text='1', url=None,
                                                                                                    callback_data='dialog_calendar:6:2023:2:1',
                                                                                                    web_app=None,
                                                                                                    login_url=None,
                                                                                                    switch_inline_query=None,
                                                                                                    switch_inline_query_current_chat=None,
                                                                                                    switch_inline_query_chosen_chat=None,
                                                                                                    callback_game=None,
                                                                                                    pay=None),
                                                                                                InlineKeyboardButton(
                                                                                                    text='2', url=None,
                                                                                                    callback_data='dialog_calendar:6:2023:2:2',
                                                                                                    web_app=None,
                                                                                                    login_url=None,
                                                                                                    switch_inline_query=None,
                                                                                                    switch_inline_query_current_chat=None,
                                                                                                    switch_inline_query_chosen_chat=None,
                                                                                                    callback_game=None,
                                                                                                    pay=None),
                                                                                                InlineKeyboardButton(
                                                                                                    text='3', url=None,
                                                                                                    callback_data='dialog_calendar:6:2023:2:3',
                                                                                                    web_app=None,
                                                                                                    login_url=None,
                                                                                                    switch_inline_query=None,
                                                                                                    switch_inline_query_current_chat=None,
                                                                                                    switch_inline_query_chosen_chat=None,
                                                                                                    callback_game=None,
                                                                                                    pay=None),
                                                                                                InlineKeyboardButton(
                                                                                                    text='4', url=None,
                                                                                                    callback_data='dialog_calendar:6:2023:2:4',
                                                                                                    web_app=None,
                                                                                                    login_url=None,
                                                                                                    switch_inline_query=None,
                                                                                                    switch_inline_query_current_chat=None,
                                                                                                    switch_inline_query_chosen_chat=None,
                                                                                                    callback_game=None,
                                                                                                    pay=None),
                                                                                                InlineKeyboardButton(
                                                                                                    text='5', url=None,
                                                                                                    callback_data='dialog_calendar:6:2023:2:5',
                                                                                                    web_app=None,
                                                                                                    login_url=None,
                                                                                                    switch_inline_query=None,
                                                                                                    switch_inline_query_current_chat=None,
                                                                                                    switch_inline_query_chosen_chat=None,
                                                                                                    callback_game=None,
                                                                                                    pay=None)], [
                                                                                                InlineKeyboardButton(
                                                                                                    text='6', url=None,
                                                                                                    callback_data='dialog_calendar:6:2023:2:6',
                                                                                                    web_app=None,
                                                                                                    login_url=None,
                                                                                                    switch_inline_query=None,
                                                                                                    switch_inline_query_current_chat=None,
                                                                                                    switch_inline_query_chosen_chat=None,
                                                                                                    callback_game=None,
                                                                                                    pay=None),
                                                                                                InlineKeyboardButton(
                                                                                                    text='7', url=None,
                                                                                                    callback_data='dialog_calendar:6:2023:2:7',
                                                                                                    web_app=None,
                                                                                                    login_url=None,
                                                                                                    switch_inline_query=None,
                                                                                                    switch_inline_query_current_chat=None,
                                                                                                    switch_inline_query_chosen_chat=None,
                                                                                                    callback_game=None,
                                                                                                    pay=None),
                                                                                                InlineKeyboardButton(
                                                                                                    text='8', url=None,
                                                                                                    callback_data='dialog_calendar:6:2023:2:8',
                                                                                                    web_app=None,
                                                                                                    login_url=None,
                                                                                                    switch_inline_query=None,
                                                                                                    switch_inline_query_current_chat=None,
                                                                                                    switch_inline_query_chosen_chat=None,
                                                                                                    callback_game=None,
                                                                                                    pay=None),
                                                                                                InlineKeyboardButton(
                                                                                                    text='9', url=None,
                                                                                                    callback_data='dialog_calendar:6:2023:2:9',
                                                                                                    web_app=None,
                                                                                                    login_url=None,
                                                                                                    switch_inline_query=None,
                                                                                                    switch_inline_query_current_chat=None,
                                                                                                    switch_inline_query_chosen_chat=None,
                                                                                                    callback_game=None,
                                                                                                    pay=None),
                                                                                                InlineKeyboardButton(
                                                                                                    text='10', url=None,
                                                                                                    callback_data='dialog_calendar:6:2023:2:10',
                                                                                                    web_app=None,
                                                                                                    login_url=None,
                                                                                                    switch_inline_query=None,
                                                                                                    switch_inline_query_current_chat=None,
                                                                                                    switch_inline_query_chosen_chat=None,
                                                                                                    callback_game=None,
                                                                                                    pay=None),
                                                                                                InlineKeyboardButton(
                                                                                                    text='11', url=None,
                                                                                                    callback_data='dialog_calendar:6:2023:2:11',
                                                                                                    web_app=None,
                                                                                                    login_url=None,
                                                                                                    switch_inline_query=None,
                                                                                                    switch_inline_query_current_chat=None,
                                                                                                    switch_inline_query_chosen_chat=None,
                                                                                                    callback_game=None,
                                                                                                    pay=None),
                                                                                                InlineKeyboardButton(
                                                                                                    text='12', url=None,
                                                                                                    callback_data='dialog_calendar:6:2023:2:12',
                                                                                                    web_app=None,
                                                                                                    login_url=None,
                                                                                                    switch_inline_query=None,
                                                                                                    switch_inline_query_current_chat=None,
                                                                                                    switch_inline_query_chosen_chat=None,
                                                                                                    callback_game=None,
                                                                                                    pay=None)], [
                                                                                                InlineKeyboardButton(
                                                                                                    text='13', url=None,
                                                                                                    callback_data='dialog_calendar:6:2023:2:13',
                                                                                                    web_app=None,
                                                                                                    login_url=None,
                                                                                                    switch_inline_query=None,
                                                                                                    switch_inline_query_current_chat=None,
                                                                                                    switch_inline_query_chosen_chat=None,
                                                                                                    callback_game=None,
                                                                                                    pay=None),
                                                                                                InlineKeyboardButton(
                                                                                                    text='14', url=None,
                                                                                                    callback_data='dialog_calendar:6:2023:2:14',
                                                                                                    web_app=None,
                                                                                                    login_url=None,
                                                                                                    switch_inline_query=None,
                                                                                                    switch_inline_query_current_chat=None,
                                                                                                    switch_inline_query_chosen_chat=None,
                                                                                                    callback_game=None,
                                                                                                    pay=None),
                                                                                                InlineKeyboardButton(
                                                                                                    text='15', url=None,
                                                                                                    callback_data='dialog_calendar:6:2023:2:15',
                                                                                                    web_app=None,
                                                                                                    login_url=None,
                                                                                                    switch_inline_query=None,
                                                                                                    switch_inline_query_current_chat=None,
                                                                                                    switch_inline_query_chosen_chat=None,
                                                                                                    callback_game=None,
                                                                                                    pay=None),
                                                                                                InlineKeyboardButton(
                                                                                                    text='16', url=None,
                                                                                                    callback_data='dialog_calendar:6:2023:2:16',
                                                                                                    web_app=None,
                                                                                                    login_url=None,
                                                                                                    switch_inline_query=None,
                                                                                                    switch_inline_query_current_chat=None,
                                                                                                    switch_inline_query_chosen_chat=None,
                                                                                                    callback_game=None,
                                                                                                    pay=None),
                                                                                                InlineKeyboardButton(
                                                                                                    text='17', url=None,
                                                                                                    callback_data='dialog_calendar:6:2023:2:17',
                                                                                                    web_app=None,
                                                                                                    login_url=None,
                                                                                                    switch_inline_query=None,
                                                                                                    switch_inline_query_current_chat=None,
                                                                                                    switch_inline_query_chosen_chat=None,
                                                                                                    callback_game=None,
                                                                                                    pay=None),
                                                                                                InlineKeyboardButton(
                                                                                                    text='18', url=None,
                                                                                                    callback_data='dialog_calendar:6:2023:2:18',
                                                                                                    web_app=None,
                                                                                                    login_url=None,
                                                                                                    switch_inline_query=None,
                                                                                                    switch_inline_query_current_chat=None,
                                                                                                    switch_inline_query_chosen_chat=None,
                                                                                                    callback_game=None,
                                                                                                    pay=None),
                                                                                                InlineKeyboardButton(
                                                                                                    text='19', url=None,
                                                                                                    callback_data='dialog_calendar:6:2023:2:19',
                                                                                                    web_app=None,
                                                                                                    login_url=None,
                                                                                                    switch_inline_query=None,
                                                                                                    switch_inline_query_current_chat=None,
                                                                                                    switch_inline_query_chosen_chat=None,
                                                                                                    callback_game=None,
                                                                                                    pay=None)], [
                                                                                                InlineKeyboardButton(
                                                                                                    text='20', url=None,
                                                                                                    callback_data='dialog_calendar:6:2023:2:20',
                                                                                                    web_app=None,
                                                                                                    login_url=None,
                                                                                                    switch_inline_query=None,
                                                                                                    switch_inline_query_current_chat=None,
                                                                                                    switch_inline_query_chosen_chat=None,
                                                                                                    callback_game=None,
                                                                                                    pay=None),
                                                                                                InlineKeyboardButton(
                                                                                                    text='21', url=None,
                                                                                                    callback_data='dialog_calendar:6:2023:2:21',
                                                                                                    web_app=None,
                                                                                                    login_url=None,
                                                                                                    switch_inline_query=None,
                                                                                                    switch_inline_query_current_chat=None,
                                                                                                    switch_inline_query_chosen_chat=None,
                                                                                                    callback_game=None,
                                                                                                    pay=None),
                                                                                                InlineKeyboardButton(
                                                                                                    text='22', url=None,
                                                                                                    callback_data='dialog_calendar:6:2023:2:22',
                                                                                                    web_app=None,
                                                                                                    login_url=None,
                                                                                                    switch_inline_query=None,
                                                                                                    switch_inline_query_current_chat=None,
                                                                                                    switch_inline_query_chosen_chat=None,
                                                                                                    callback_game=None,
                                                                                                    pay=None),
                                                                                                InlineKeyboardButton(
                                                                                                    text='23', url=None,
                                                                                                    callback_data='dialog_calendar:6:2023:2:23',
                                                                                                    web_app=None,
                                                                                                    login_url=None,
                                                                                                    switch_inline_query=None,
                                                                                                    switch_inline_query_current_chat=None,
                                                                                                    switch_inline_query_chosen_chat=None,
                                                                                                    callback_game=None,
                                                                                                    pay=None),
                                                                                                InlineKeyboardButton(
                                                                                                    text='24', url=None,
                                                                                                    callback_data='dialog_calendar:6:2023:2:24',
                                                                                                    web_app=None,
                                                                                                    login_url=None,
                                                                                                    switch_inline_query=None,
                                                                                                    switch_inline_query_current_chat=None,
                                                                                                    switch_inline_query_chosen_chat=None,
                                                                                                    callback_game=None,
                                                                                                    pay=None),
                                                                                                InlineKeyboardButton(
                                                                                                    text='25', url=None,
                                                                                                    callback_data='dialog_calendar:6:2023:2:25',
                                                                                                    web_app=None,
                                                                                                    login_url=None,
                                                                                                    switch_inline_query=None,
                                                                                                    switch_inline_query_current_chat=None,
                                                                                                    switch_inline_query_chosen_chat=None,
                                                                                                    callback_game=None,
                                                                                                    pay=None),
                                                                                                InlineKeyboardButton(
                                                                                                    text='26', url=None,
                                                                                                    callback_data='dialog_calendar:6:2023:2:26',
                                                                                                    web_app=None,
                                                                                                    login_url=None,
                                                                                                    switch_inline_query=None,
                                                                                                    switch_inline_query_current_chat=None,
                                                                                                    switch_inline_query_chosen_chat=None,
                                                                                                    callback_game=None,
                                                                                                    pay=None)], [
                                                                                                InlineKeyboardButton(
                                                                                                    text='27', url=None,
                                                                                                    callback_data='dialog_calendar:6:2023:2:27',
                                                                                                    web_app=None,
                                                                                                    login_url=None,
                                                                                                    switch_inline_query=None,
                                                                                                    switch_inline_query_current_chat=None,
                                                                                                    switch_inline_query_chosen_chat=None,
                                                                                                    callback_game=None,
                                                                                                    pay=None),
                                                                                                InlineKeyboardButton(
                                                                                                    text='28', url=None,
                                                                                                    callback_data='dialog_calendar:6:2023:2:28',
                                                                                                    web_app=None,
                                                                                                    login_url=None,
                                                                                                    switch_inline_query=None,
                                                                                                    switch_inline_query_current_chat=None,
                                                                                                    switch_inline_query_chosen_chat=None,
                                                                                                    callback_game=None,
                                                                                                    pay=None),
                                                                                                InlineKeyboardButton(
                                                                                                    text=' ', url=None,
                                                                                                    callback_data='dialog_calendar:0:-1:-1:-1',
                                                                                                    web_app=None,
                                                                                                    login_url=None,
                                                                                                    switch_inline_query=None,
                                                                                                    switch_inline_query_current_chat=None,
                                                                                                    switch_inline_query_chosen_chat=None,
                                                                                                    callback_game=None,
                                                                                                    pay=None),
                                                                                                InlineKeyboardButton(
                                                                                                    text=' ', url=None,
                                                                                                    callback_data='dialog_calendar:0:-1:-1:-1',
                                                                                                    web_app=None,
                                                                                                    login_url=None,
                                                                                                    switch_inline_query=None,
                                                                                                    switch_inline_query_current_chat=None,
                                                                                                    switch_inline_query_chosen_chat=None,
                                                                                                    callback_game=None,
                                                                                                    pay=None),
                                                                                                InlineKeyboardButton(
                                                                                                    text=' ', url=None,
                                                                                                    callback_data='dialog_calendar:0:-1:-1:-1',
                                                                                                    web_app=None,
                                                                                                    login_url=None,
                                                                                                    switch_inline_query=None,
                                                                                                    switch_inline_query_current_chat=None,
                                                                                                    switch_inline_query_chosen_chat=None,
                                                                                                    callback_game=None,
                                                                                                    pay=None),
                                                                                                InlineKeyboardButton(
                                                                                                    text=' ', url=None,
                                                                                                    callback_data='dialog_calendar:0:-1:-1:-1',
                                                                                                    web_app=None,
                                                                                                    login_url=None,
                                                                                                    switch_inline_query=None,
                                                                                                    switch_inline_query_current_chat=None,
                                                                                                    switch_inline_query_chosen_chat=None,
                                                                                                    callback_game=None,
                                                                                                    pay=None),
                                                                                                InlineKeyboardButton(
                                                                                                    text=' ', url=None,
                                                                                                    callback_data='dialog_calendar:0:-1:-1:-1',
                                                                                                    web_app=None,
                                                                                                    login_url=None,
                                                                                                    switch_inline_query=None,
                                                                                                    switch_inline_query_current_chat=None,
                                                                                                    switch_inline_query_chosen_chat=None,
                                                                                                    callback_game=None,
                                                                                                    pay=None)]]),
                      forward_date=None, forward_from=None, forward_from_chat=None, forward_from_message_id=None,
                      forward_sender_name=None, forward_signature=None, user_shared=None),
    inline_message_id=None,
    data='dialog_calendar:6:2023:2:22',
    game_short_name=None
    )
